# Generated by Django 5.1.7 on 2025-03-13 08:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_id', models.IntegerField(unique=True)),
                ('number_of_installment', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('installment_is_active', models.BooleanField(default=True)),
                ('installment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.user')),
            ],
        ),
    ]
